### ISSUE TITLE
Snippets manager text legibility on dark themes

### ISSUE THREAD

**Issue by glepretre** [chuyik/brackets-snippets#1]
Hi,

I am trying your extension and its brand new snippets manager!

I would just point out that the text shadows in the manager reduce legibility on dark themes (see attached image :wink:)

![selection_002](https://cloud.githubusercontent.com/assets/5930831/6062169/d7c9cfd0-ad4d-11e4-95c8-81beaba264a5.png)

**Comment by chuyik** [comment]
Thanks for trying and bringing it up!
I didn't notice that since I never use the dark theme, so I would try to make it perfect on dark theme in next release. XD

**Comment by glepretre** [comment]
Thanks! :smile:
