### ISSUE TITLE
Update button not clickable

### ISSUE THREAD

**Issue by onetrev** [chuyik/brackets-snippets#11]
I think this may have happened with the last update as well, but for sure the "Update" button in Brackets extension manager is not clickable. It shows up but is faded out. I was able to confirm this on another machine as well.

Not sure if this helps but I think you need to add this to your .json file if you don't have it already:

`
"engines": {
      "brackets": ">=1.0.0"
    },
`

**Comment by chuyik** [comment]
Thanks for testing it out!
I try your method and it works, tested on a virtual machine and it can update now.
