### ISSUE TITLE
embedded ruby not working

### ISSUE THREAD

**Issue by esukex** [chuyik/brackets-snippets#13]
hi, love the extension, very intuitive and useful, however when i select embedded ruby and create a new rule, it does not come into effect. i have tested it with html and all is working, just doesnt seem to recognize that i am using embedded ruby.

hope this can be fixed!

thanks

esukex

**Comment by chuyik** [comment]
Hi because embedded ruby includes HTML code and ruby code, if the cursor is on HTML code, you could see the HTML snippets. Similarly, ruby snippets will show up if the cursor is on ruby part.

But since the HTML and ruby code glue together very often, I think the snippets of `embedded ruby` scope should be shown up no matter where the cursor is in `.erb` files.

How do you think?

**Comment by esukex** [comment]
as far as i know, all ruby code in embedded ruby documents are encased
within <% %> or similar tags, it might be best to include this in the HTML
tags so that ruby can be written and then show ruby tags within these
sections.

that may be too complicated however, so maybe both should show at any point
in the file.
i should note that i am a beginner programmer, and so my opinion should not
carry too much weight.

i appreciate your quick response, and i can now at least temporarily fix
the behavior locally.

thank you

jackson

**Comment by chuyik** [comment]
In current version, if you type inside <%%>, the `ruby` snippets would show up, and if you type inside html tags, the `html` snippets would show up. It depends on the context.

But I think the `Embedded Ruby` snippets (Not the same with `ruby` snippets) should be shown up anywhere inside the .erb file, which it could be fixed easily.

**Comment by esukex** [comment]
yes, i agree.

sorry, its past 1am here, so i cant reply quickly from now on.

thank you though.

jackson

**Comment by chuyik** [comment]
Sleep is important :)
