### ISSUE TITLE
SCSS snippets not working

### ISSUE THREAD

**Issue by SaltPacket** [chuyik/brackets-snippets#14]
Brackets 1.2 and Brackets Snippets 1.6.3

No snippet hints show in SCSS files, including snippets marked with the SCSS scope.

**Comment by chuyik** [comment]
Thanks for the report, it's been fixed in 1.6.4.

**Comment by carobe** [comment]
I use the last version (1.7.2) and snippets not working in SCSS files.

**Comment by chuyik** [comment]
@carobe But works in other type of files?

**Comment by carobe** [comment]
Yes, ii works with css, html and js files.

**Comment by chuyik** [comment]
@carobe Could you show me the snippet content?
