### ISSUE TITLE
Ugly buttons when using dark themes

### ISSUE THREAD

**Issue by gruppler** [chuyik/brackets-snippets#16]
When using a dark theme, the 'active' buttons look...not good. Is there a way to use colors or button styles defined in the theme?

![snippets](https://cloud.githubusercontent.com/assets/301190/6557332/943c05ce-c64a-11e4-8763-623064a25adc.png)

Coming from Sublime, I'm really happy to have found this plugin. Thanks for all the work you've put into it!

**Comment by chuyik** [comment]
God that UI is terrible...
Thanks for the report, I will fix it soon!
