### ISSUE TITLE
Support additional snippets w/o needing to mod the core file?

### ISSUE THREAD

**Issue by cfjedimaster** [chuyik/brackets-snippets#17]
On the readme, it says if you want to add your own snippets, you need to fork the project and add them to the main file. What about simply letting people add *additional* files? I don't want to fork the project just to add my own snippets.

**Comment by chuyik** [comment]
Hi @cfjedimaster, if you want to add multiple snippets for your own use, you could use the `import` function(`Export` existed snippets first if you're confused about the syntax).
But `Snippet Library` is different, everyone could contribute to it by forking project or simply paste the snippets by creating an issue.

**Comment by cfjedimaster** [comment]
Ah - I misread the readme. Sorry - and feel free to close.
