### ISSUE TITLE
Scroll bar not working

### ISSUE THREAD

**Issue by theo333** [chuyik/brackets-snippets#18]
Scroll bar not working, so I am not able to use your extension.  Can't scroll down to see the snippets. This is all I can see.  Looks like it is a helpful extension once I get it working.  I am on a Mac.  Thanks. 
(I am new here, so I hope this is the right place to put this issue.)

![screenshot 2015-03-10 17 15 04](https://cloud.githubusercontent.com/assets/11414429/6585562/076eda18-c749-11e4-8587-37bf8d01a766.png)

**Comment by chuyik** [comment]
Hi @theo333, welcome to Github!

I am also using Mac, but it's weird I've never seen this, I think the CSS may be polluted by some other things.
Could you please provide the version of Brackets, and the name of theme you're using?

**Comment by theo333** [comment]
Hi @chuyik, thanks for the welcome!  :-)

Theme:  Themes for Brackets Sunburst
Brackets Release 1.2 build 1.2.0-15697

Thanks!

**Comment by chuyik** [comment]
Hi @theo333, I just try to use the theme you mentioned, but nothing really changes. Hope anyone else could help test it.

**Comment by theo333** [comment]
@chuyik  OK.  Perhaps there is a conflict with some other extension that I have installed.  Would that be a possibility?

**Comment by chuyik** [comment]
@theo333 Yeah, I think so. Maybe you could try to remove some extensions for testing, by doing that, you just need to move some of the extension folders to somewhere else.

Here's steps if you wonder:
1. Select `Help` -> `Show Extensions Folder`
2. Open `user` folder, you will see the folders of extensions you've installed
3. Try to move some of those to other places, and reload your Brackets
4. Back and forth to test out which is conflicted with

**Comment by theo333** [comment]
@chuyik Yes,  I will work on this over the next few days and let you know. Thanks for the instructions. Very helpful. Have a great weekend!
