### ISSUE TITLE
Tab is no longer working after installing the extension

### ISSUE THREAD

**Issue by simmu** [chuyik/brackets-snippets#2]
Hi, thanks for the extension! 

I really want to use it for my current project, unfortunately I can't use the 'tab' on the editor after I have it installed. The tab works again by uninstalling it. :(

I have the latest brackets - Release 1.1 build 1.1.0-15558 (release ea908cae5).

**Comment by chuyik** [comment]
Thanks for feedback, have you tried to reload brackets after install?

Reload shortcut: F5(Win) or Command + R(Mac)

**Comment by chuyik** [comment]
Sorry for the inconvenience before, now it's fixed and you could reinstall it without reload brackets.

**Comment by glepretre** [comment]
I still have this issue :worried: 

<kbd>Tab</kbd> &nbsp; and &nbsp; <kbd>Alt</kbd> + <kbd>Tab</kbd> don't work

**Comment by simmu** [comment]
Hi Edward, thanks for the quick response. I reinstalled it, but the tab still not working. :(

**Comment by chuyik** [comment]
@glepretre @simmu Hi there, I think you missed to set
```
"insertHintOnTab": true,
```
In `Debug` -> `Open Preferences File`, which is option brought by Brackets.

If not set, the snippets from my extension still works, but the default snippets from Brackets itself not.
If set, both should work which tested on my clean Brackets, would you mind test it again? Thanks!!

**Comment by simmu** [comment]
@chuyik I updated the brackets.json, unfortunately its still not working for me. I wonder if it has a conflict with other extensions?

**Comment by simmu** [comment]
@chuyik  I remove all my extensions and reinstall brackets-snippets but the tab still not working. I will try to do a clean install of brackets and see if it will work.

**Comment by chuyik** [comment]
@simmu No I've targeted some issuesnow, it should be fixed a hour later, sorry for that.

**Comment by chuyik** [comment]
@simmu Hi the extension is updated, would you mind give it another try?

**Comment by simmu** [comment]
@chuyik Hey the tab is working :) and the extension works like a charm. Thank you!

**Comment by tuckQ** [comment]
Tab is not working on environment, too. 
Here are what I did,
1. Tried both installation through Brackets' extension manager as well as github. 
2. Disable all the other plugins installed.

Is there any other work around I should try?
