### ISSUE TITLE
Support current editor's indentation style and size

### ISSUE THREAD

**Issue by PhiLhoSoft** [chuyik/brackets-snippets#20]
When the extension inserts a snippet, it should look at the current editor's indentation settings: using tabs or spaces, and if spaces, their number.

Then it should adjust the snippet to insert it with proper indentation.

Currently, if a snippet is defined with two spaces indentation, it is inserted as it, instead of four spaces (if set in Brackets' settings) or one tab.

Can be done either via some heuristic (some spaces more than previous line => one indentation level) or by adding a special character (\t for example...) in the saved snippet. The former has the advantage of being backward compatible with existing snippets, the latter is more flexible (I often use two indentation levels to mark a line continuation, ie. the split of a long line)..

**Comment by chuyik** [comment]
Cool, I'll look into it and thanks for your advice!

**Comment by chuyik** [comment]
Duplication of #28

**Comment by PhiLhoSoft** [comment]
It is not important, but it is a bit the way around: #28 is a duplicate of my issue, not the reverse. Should have been the duplicate that have been closed.

**Comment by chuyik** [comment]
@PhiLhoSoft Yeah sorry!! I should check the date (,,ﾟДﾟ)

**Comment by chuyik** [comment]
Should be fixed in 1.8 d(`･∀･)b
