### ISSUE TITLE
Loosing modifications when going to another snippet

### ISSUE THREAD

**Issue by PhiLhoSoft** [chuyik/brackets-snippets#21]
In the snippet manager, if I modify a snippet, then click on another one on the left column, I immediately change to the new one, loosing the modifications made on the previous one.

I suggest the current modifications to be automatically saved. Or to ask confirmation to the user (Do you want to save the current changes? Yes / No).
Maybe add an option to choose between the two behaviors... :-)

**Comment by chuyik** [comment]
Yeah that will be more friendly :)

I think automatically saving may confuse users and lead to more unnecessary write operations, maybe just a prompt should be fine.

**Comment by chuyik** [comment]
Hi @PhiLhoSoft, I'm happy to release 1.8 and this should be fixed!
