### ISSUE TITLE
Snippets saving then dissapear

### ISSUE THREAD

**Issue by awakekat** [chuyik/brackets-snippets#22]
Recently downloaded. I have emmet installed and know there is an issue with that. 
However, I am going through the process of creating a new snippet:
Trigger: hcom
Description: HTML Comment
Scope: HTML
Text: 
What is the difference between 'Save' and 'Save and Create'?
It does not matter which button I choose, when I close Brackets or close to refresh - the ones I created disappear. In my book save is Save forever until I delete. What's up with this feature? If I have to manually add this to a local file - where is that located?

**Comment by chuyik** [comment]
Hi @awakekat, `Save` means saving the editing snippet, `Save and Create` means save and start create next one, both are persistent.
All the datas are saved in `brackets.json`(Open it via `Debug` -> `Show Preferences File`), you could watch the contents of this file if it's modified when a snippet saved.
