### ISSUE TITLE
tabs in snippet text

### ISSUE THREAD

**Issue by OfficialBAMM** [chuyik/brackets-snippets#28]
Hey there,

I would love to use tabs instead of spaces in the snippet text. Currently I'm just copy pasting, but it would be a small useful addition IMHO.

OfficialBAMM

**Comment by eightygrit** [comment]
+1

**Comment by CupOfTea696** [comment]
Maybe it should just use whatever indentation settings you have set in your Brackets preferences? Because mine is set to 4 spaces rather than the default 2 in all snippets.

**Comment by ethangodt** [comment]
Yes, please

**Comment by chuyik** [comment]
Should be fixed in 1.8 d(`･∀･)b

**Comment by OfficialBAMM** [comment]
Nice! Keep up the good work !:)
