### ISSUE TITLE
Tag trigger problem

### ISSUE THREAD

**Issue by donPuerto** [chuyik/brackets-snippets#29]
im having a problem in triggering a TAG key. It seems to me it does not work. I tried already the blog suggestion to debug reload with and without extension and it does not work either.

I tried also to tick this on and off but nothing happen.
![insert snippets on tab check mark](https://cloud.githubusercontent.com/assets/9329005/6880637/8ad9a3f6-d577-11e4-8fb4-69a028d1e88e.PNG)

I also noted some little problem... See attached.
![restore button now being view in full](https://cloud.githubusercontent.com/assets/9329005/6880643/b2017b2a-d577-11e4-8565-c23935df1ac2.PNG)

I believe there is a bug on this. By the way i intalled today the brackets and EDWARD CHU SNIPPETS PLUGIN

**Comment by chuyik** [comment]
Sorry for the late response, does it work now?

**Comment by chuyik** [comment]
Close for not response.
