### ISSUE TITLE
JS Snippets Not Expanding

### ISSUE THREAD

**Issue by G3-Logic** [chuyik/brackets-snippets#3]
Hi + great extension! Having a problem in JavaScript however. Will not show shortcuts or expand sometimes and I think it has something to do with white space (blank lines) in the code. I leave blank lines sometimes to separate out sections as I'm working and it seems like this may be causing a problems at times. Can't put my finger on it exactly. Wondering if you have any insight.  Doesn't seem to be a problem in HTML or CSS.

Thanks in advance! -Guy Scott

**Comment by chuyik** [comment]
Hi thanks for trying!
I think you're saying the hints won't show up if your code did not separate from the former word with a white space, and that's true, Sublime Text behaves the same way.

And you also say the hints won't expand, I didn't not reproduce the problem, would you show me some code help me reproduce it?

**Comment by G3-Logic** [comment]
That did it! 
Looks like maybe some of my line-breaks are wonky. Typed a space and all
 good. May be time to clean up my templates:)Hey, while I have 
your ear, I typically like to create my CSS right on the HTML page I'm 
working with, rather than switching back and forth between files. Not a 
biggie, but I see scope is determined by page file extension, so CSS 
snippets won't trigger, even though I'm inside of a style tag. Any work 
around?Thanks again for your time. Brackets newbee so still 
getting my feet underneath me a bit...Guy Scott



Guy F. Scott III
G3 Logic Media Design
207.350.7242
Edward Chu wrote:Hi thanks for trying!
I think you're saying the hints won't show up if your code did not 
separate from the former word with a white space, and that's true, 
Sublime Text behaves the same way.

And you also say the hints won't expand, I didn't not reproduce the 
problem, would you show me some code help me reproduce it?

—Reply
 to this email directly or view
 it on GitHub.

**Comment by chuyik** [comment]
Welcome to Brackets family ha!
The upcoming version will recognize your trigger even it's after some punctuations, not only space.
You mentioned the style tag issue which I also notice that, but I seriously think it's not a good idea to write css inlinely. However I would try some time to make a solution after the Chinese new year. :wink:

**Comment by G3-Logic** [comment]
THANKS! Been 
using Coda for quite some time. But the last few updates have gotten 
extremely buggy and I just don't have time to mess with it. Decided to 
re-visit Brackets and wow... its really come a long way!Sorry, 
didn't mean inline styles (no-no!) I meant I use an internal style sheet
 inside of the HTML document (as opposed to an external style sheet). So
 when I'm editing the CSS, the CSS snippets don't appear... I guess 
because it is in the HTML doc. If you like, I can send an example.Anyway,
 Happy New Year + thanks again!!!Guy



Guy F. Scott III
G3 Logic Media Design
207.350.7242
Edward Chu wrote:Welcome to Brackets family ha!
The upcoming version will recognize your trigger even it's after some 
punctuations, not only space.
You mentioned the style tag issue which I also notice that, but I 
seriously think it's not a good idea to write css inlinely. However I 
would try some time to make a solution after the Chinese new year. 

—Reply
 to this email directly or view
 it on GitHub.

**Comment by chuyik** [comment]
Oh I forget its name is internal style sheet lol, actually I mean the same thing but use the wrong term.
Thanks for your blessing!

**Comment by G3-Logic** [comment]
No, you were 
correct. Inline styles allow the CSS to be inserted into the HTML 
mark-up... which is a no-no.Internal style sheet is when you 
define all of your styles in the head of the page between 
<style></style> tags. Brackets recognizes this and will give
 code hints for internal style sheets when you are working between those
 tags. However the snippets don't show up... presumably because the doc 
is an html file.You can see here Brackets CSS code hints are 
displaying properly in the internal style sheet of this HTML doc: 



Guy F. Scott III
G3 Logic Media Design
207.350.7242
Edward Chu wrote:Oh I forget its name is internal style sheet lol, 
actually I mean the same thing but use the wrong term.
Thanks for your blessing!

—Reply
 to this email directly or view
 it on GitHub.

**Comment by chuyik** [comment]
Yeah I definitely know the differences between inline css and internal style sheet, I just mess up with the terms.
Since I write the snippets filtering and showing logic with some lower APIs rather than simply using the HintManager API, and I filter snippets according to file types, so css snippets won't show up in html.
But it's solvable, I just do a little more things like detecting the cursor position and context.. etc.

**Comment by G3-Logic** [comment]
LOL! 
Yes, I was pretty sure you knew the difference! Was afraid that I wasn't
 making myself clear...
  
Thanks again!!!
  
Guy 



Guy F. Scott III
G3 Logic Media Design
207.350.7242
Edward Chu wrote:Yeah I definitely know the differences between inline 
css and internal style sheet, I just mess up with the terms.
Since I write the snippets filtering and showing logic with some lower 
APIs rather than simply using the HintManager API, and I filter snippets
 according to file types, so css snippets won't show up in html.
But it's solvable, I just do a little more things like detecting the 
cursor position and context.. etc.

—Reply
 to this email directly or view
 it on GitHub.

**Comment by chuyik** [comment]
Actually your explanations are very clear haha, and you are welcome~

**Comment by G3-Logic** [comment]
HEY, just 
updated and you snippets are detecting my internal style sheet! WELL 
DONE + THANKS!!!



Guy F. Scott III
G3 Logic Media Design
207.350.7242
Edward Chu wrote:Yeah I definitely know the differences between inline 
css and internal style sheet, I just mess up with the terms.
Since I write the snippets filtering and showing logic with some lower 
APIs rather than simply using the HintManager API, and I filter snippets
 according to file types, so css snippets won't show up in html.
But it's solvable, I just do a little more things like detecting the 
cursor position and context.. etc.

—Reply
 to this email directly or view
 it on GitHub.
