### ISSUE TITLE
Snippets for Yii Framework

### ISSUE THREAD

**Issue by joshijitendra** [chuyik/brackets-snippets#33]
I am planning to create snippets for [Yii Framework] (http://yiiframework.com/) but do not want them to come in the way of other PHP developers using other frameworks or basic PHP code. What would be the best way to approach this problem?

**Comment by chuyik** [comment]
Hi @joshijitendra, sorry for the late reply! 
The simplest way is to send your snippets to me, I will handle the rest by adding `tag` to each snippet for separation.

**Comment by joshijitendra** [comment]
Thank you for your reply. I just need to submit pull request right?

**Comment by chuyik** [comment]
Yes please!

Edward Chu
