### ISSUE TITLE
Support for special tab/space characters

### ISSUE THREAD

**Issue by PictoLogic** [chuyik/brackets-snippets#40]
I'd like using "\t","\s" in a snippet to specify the number of tabs/spaces.
For example:
`echo "<pre>";
\tprint_r(${1});
echo "</pre>";`
or
`echo "<pre>";
\t\tvar_dump(${1});
echo "</pre>";`

**Comment by chuyik** [comment]
Hi @PictoLogic, thanks for the advice, tab character will be supported soon!

**Comment by chuyik** [comment]
Close this (duplication of #28)
