### ISSUE TITLE
Extremely tiny graph bug :)

### ISSUE THREAD

**Issue by OfficialBAMM** [chuyik/brackets-snippets#41]
![](http://i.imgur.com/0epsNvN.png)
I'm using Monokai Dark Soda theme.

Also, a small thingy that might need fixing: 
![](http://i.imgur.com/ui6IPs1.png)
I can't see the bottom of the info popup.

Thanks for the update :+1:! These things aren't massive, I just thought I'd let you know :). Close if you like.

**Comment by chuyik** [comment]
Hi @OfficialBAMM thanks for your feedback! I'm glad to know and they're fixed in 1.8.1.
