### ISSUE TITLE
Tabs won't advance to next variable?

### ISSUE THREAD

**Issue by bobrocke** [chuyik/brackets-snippets#43]
First, this extension looks like first-class work! It is implemented in a very smooth, Brackets-like way. Nice job!

I have `Select next variable` left at the default (tabs)

And I've created this snippet with a trigger of `ai` and a scope of `any`:
`![${1:app} Icon](/images/icons/$2.jpg){.image-${3:right} .image-${4:25}}$5`

Typing `ai tab` enters the snippet as expected with the variable `app` selected. Typing over the variable and press tab replaces the variable, but then inserts a tab rather than jumping to the next variable.

Do I have the snippet coded wrong?

**Comment by bobrocke** [comment]
The supplied Anchor Tag snippet fires and inserts, but the entire snippet is selected and the variables can't be entered:

![tester html www grav dev brackets](https://cloud.githubusercontent.com/assets/2962426/7902164/3b81bebe-077d-11e5-82bc-a6dec6a22cb7.jpg)

**Comment by bobrocke** [comment]
I'm not using Emmet.

**Comment by chuyik** [comment]
Hi thanks for trying!
The syntax of cursor should be ${NUMBER}, it means the correct snippet is as follows:
```
![${1:app} Icon](/images/icons/${2}.jpg){.image-${3:right} .image-${4:25}}${5}
```
Please compare the slight differences.

And the second question you mentioned, I can't see why it happens.

**Comment by bobrocke** [comment]
Subtle difference, yes!

And that fixed it. Thank you!
