### ISSUE TITLE
Where are user written snippets stored?

### ISSUE THREAD

**Issue by bobrocke** [chuyik/brackets-snippets#45]
I'd like to be able to share snippets between computers via Dropbox, but my laptop does not pick up this extension if I share the `~/Dropbox/Application Support/brackets/extensions/user/edc.brackets-snippets` folder from my dektop.

**Comment by bobrocke** [comment]
Digger around more, it looks like they are saved in `brackets.json`.

**Comment by chuyik** [comment]
Yes you're right
