### ISSUE TITLE
Not working on synced laptop

### ISSUE THREAD

**Issue by bobrocke** [chuyik/brackets-snippets#47]
I have Bracket Snippets working on my desktop and sharing extensions via Dropbox with my laptop. The extension shows as installed on the laptop, but has no icon in the right margin for use.

**Comment by chuyik** [comment]
I try to sync the `brackets.json` between OSX and Windows macthine, and both work well.

So I think if the `brackets.json` breaks some other extensions, it would be great if you could post some logs here.

**Comment by bobrocke** [comment]
OK, so I have brackets.json and all my extensions synced between my desktop and my laptop via a folder and symlinks on Dropbox. Everything works fine on the desktop.

But on the laptop, brackets-snippets does not even show it's launch icon on the right-hand toolbar.

From the Extension Manager dialog, I see the brakes-snippets is loaded.

So why won't it work on the laptop at all?

**Comment by chuyik** [comment]
Have you checked the error messages on webtools (open via `Debug` -> `Show Developer Tools`)?

**Comment by bobrocke** [comment]
Nothing interesting there. A bunch of unrelated depreciation warnings.

Bob
------------------------------------------------------------------------
Robert J. Rockefeller
www.bobrockefeller.com <http://www.bobrockefeller.com>
Richmond Hill, GA

**Comment by chuyik** [comment]
Eh that's weird.. I couldn't come up with any reason why not, sorry.
Unless you have not open any files in Brackets.

**Comment by bobrocke** [comment]
That's why! I had no files open and didn't think about that being 
important. Works fine, now. :)

Bob
------------------------------------------------------------------------
Robert J. Rockefeller
Richmond Hill, GA
www.bobrockefeller.com <http://www.bobrockefeller.com>

**Comment by chuyik** [comment]
Yeah cool!
