### ISSUE TITLE
Outdated screenshot?

### ISSUE THREAD

**Issue by sbrl** [chuyik/brackets-snippets#55]
In this repo's readme, there's a pair of buttons in the library screenshot named "Library" and "Settings". They don't appear for me. Have they been removed?

**Comment by agalazis** [comment]
+1 I agree not sure where to find the library button

**Comment by agalazis** [comment]
note that in order to get the library button you have to press cancel if you have already selected a snippet.

**Comment by sbrl** [comment]
Right. Thanks!
