### ISSUE TITLE
Snippets not working in <script>

### ISSUE THREAD

**Issue by OfficialBAMM** [chuyik/brackets-snippets#6]
Sorry if I'm just being a idiot, but i can't seem to get the plugin working for javascript commands in a html page.
Maybe this feature isn't added yet(or won't), but I feel like I'm doing something wrong!

OfficalBAMM

**Comment by chuyik** [comment]
Sorry for making you confusing and your guess is right, now snippets are filtered by the editing file type.
See [Todo#1](https://github.com/chuyik/brackets-snippets#todo)

**Comment by OfficialBAMM** [comment]
Ah! Thanks. Should have checked the Todo list! keep up the good work

**Comment by chuyik** [comment]
Hi @OfficialBAMM, snippets now working in <style> or <script>, please check out the new version :)

**Comment by OfficialBAMM** [comment]
Hey @chuyik, Amazing work dude :+1: ! What about PHP? I just create a comment section and then it works perfectly, so it isn't much of a hassle ;p.

**Comment by chuyik** [comment]
@OfficialBAMM Sorry I don't know anything about PHP, could you show me some codes about comment section and tell me how to test that?

**Comment by OfficialBAMM** [comment]
For example for the for loop I have the following code: 
for($i=${1:0}; $i ${2:< length}; $i++)
{
${3:code}
}

Before the 1.6 update i could type in "//for" and hit tab to execute the plugin. But that doesn't work anymore. I am unable to execute any PHP snippet. JavaScript works perfectly though! I hope I am clear enough for you, it's been a long time since I wrote English ;p.

**Comment by chuyik** [comment]
@OfficialBAMM Thanks for the description, it should be fixed now :)

**Comment by OfficialBAMM** [comment]
Nice! It works! Great job :)
