### ISSUE TITLE
Tab indent - snippet not expanding

### ISSUE THREAD

**Issue by onetrev** [chuyik/brackets-snippets#9]
If I indent my code using the **tab** key then snippet code hints do not show up. This occurs in CSS, PHP, and JS. I have not tested other scopes. If I use space bar to indent my code, then all is good.

Similarly, if I finish a block of HTML that was indented with the tab key, hit enter, and thus the next line is indented, snippet code hints will not show up either. I have to hit delete to get back to column 1 of that line in order for the code hints to work again.

Let me know if you need a demo or more info. Hope this can be fixed, this is such a great extension, one of the key reasons I finally switched from Sublime Text to Brackets. Thank you!!

System Info: Brackets 1.1; Windows 8.1

**Comment by onetrev** [comment]
If anyone else is having this problem, for now the best bet is to just convert to using all spaces instead of tabs. This extension is probably the fastest way to convert your files: 
https://github.com/dsbonev/whitespace-normalizer

And this is handy if you want to double check if your file has spaces or tabs:
https://github.com/DennisKehrig/brackets-show-whitespace

**Comment by chuyik** [comment]
Thanks for the feedback, Tab indentation would be supported in the next version.

**Comment by chuyik** [comment]
Hi @onetrev, Tab indentation is supported now, please check out the new version!

**Comment by onetrev** [comment]
Works perfectly thanks! Awesome plugins thanks for continuing to make it better.
